version: '3'

services:
  app: 
    image: delirehberi/php7-symfony:7.4
    environment:
      DB_HOSTNAME: mysql
      DB_PORT: 3306
      DB_NAME: legacy
      DB_USERNAME: legacy
      DB_PASSWORD: legacy
    platform: linux/x86_64
    volumes:
      - ./app:/app
      - ./docker/php.www.conf:/etc/php7/php-fpm.d/www.conf
  server:
    image: nginx:1.16.1
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:5.7.31
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: legacy
      MYSQL_USER: legacy
      MYSQL_PASSWORD: legacy
    volumes:
      - ./app/:/app
    ports:
      - "3306:3306"
    platform: linux/x86_64
